"""Where settings, caches, logs and downloads land on each desktop.

The Linux branches of this module cannot be exercised on the development machine,
so they are pinned here instead: every function is driven through monkeypatched
platform predicates.  Absolute-path checks use ``tmp_path`` rather than literal
POSIX strings, because ``PureWindowsPath("/etc").is_absolute()`` is false and a
hard-coded ``"/home/u"`` would silently take the fallback branch on Windows.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from asmr_lrc import platform_paths
from asmr_lrc.platform_paths import (
    APP_NAME,
    APP_SLUG,
    app_data_directory,
    cache_directory,
    default_download_root,
    downloads_directory,
    player_cache_directory,
    settings_path,
    state_directory,
)

XDG_VARIABLES = ("XDG_CONFIG_HOME", "XDG_CACHE_HOME", "XDG_STATE_HOME")


@pytest.fixture
def home(tmp_path, monkeypatch):
    """A throwaway home directory for the fallback branches."""
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: tmp_path))
    # Computed at import time from the real home, so patching Path.home is not
    # enough to move it.
    monkeypatch.setattr(platform_paths, "_XDG_USER_DIRS", tmp_path / ".config" / "user-dirs.dirs")
    return tmp_path


@pytest.fixture
def linux(monkeypatch, home):
    monkeypatch.setattr(platform_paths, "is_windows", lambda: False)
    monkeypatch.setattr(platform_paths, "is_macos", lambda: False)
    for name in (*XDG_VARIABLES, "LOCALAPPDATA"):
        monkeypatch.delenv(name, raising=False)
    return home


@pytest.fixture
def windows(monkeypatch, home):
    monkeypatch.setattr(platform_paths, "is_windows", lambda: True)
    monkeypatch.setattr(platform_paths, "is_macos", lambda: False)
    monkeypatch.delenv("LOCALAPPDATA", raising=False)
    return home


def test_windows_directories_follow_localappdata(windows, tmp_path, monkeypatch):
    root = tmp_path / "Local"
    monkeypatch.setenv("LOCALAPPDATA", str(root))
    assert app_data_directory() == root / APP_NAME
    assert cache_directory() == root / APP_NAME / "cache"
    assert state_directory() == root / APP_NAME / "state"


def test_windows_falls_back_under_home_without_localappdata(windows):
    assert app_data_directory() == windows / "AppData" / "Local" / APP_NAME


def test_linux_directories_follow_the_xdg_base_directories(linux, tmp_path, monkeypatch):
    for name in XDG_VARIABLES:
        monkeypatch.setenv(name, str(tmp_path / name.lower()))
    assert app_data_directory() == tmp_path / "xdg_config_home" / APP_SLUG
    assert cache_directory() == tmp_path / "xdg_cache_home" / APP_SLUG
    assert state_directory() == tmp_path / "xdg_state_home" / APP_SLUG


def test_linux_defaults_match_the_base_directory_spec(linux):
    assert app_data_directory() == linux / ".config" / APP_SLUG
    assert cache_directory() == linux / ".cache" / APP_SLUG
    assert state_directory() == linux / ".local" / "state" / APP_SLUG


@pytest.mark.parametrize("value", ["", "   ", "relative/config"])
def test_relative_or_blank_xdg_values_are_ignored(linux, monkeypatch, value):
    # The spec says relative values must be ignored; honouring one would scatter
    # settings through whatever directory the launcher happened to start in.
    monkeypatch.setenv("XDG_CONFIG_HOME", value)
    assert app_data_directory() == linux / ".config" / APP_SLUG


def test_derived_paths_hang_off_the_base_directories(linux):
    assert settings_path() == app_data_directory() / "settings.json"
    assert player_cache_directory() == cache_directory() / "player"
    assert default_download_root() == downloads_directory() / APP_NAME


def write_user_dirs(home: Path, body: str) -> None:
    path = platform_paths._XDG_USER_DIRS
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def test_localized_download_directory_is_honoured(linux, tmp_path):
    # xdg-user-dirs writes the localized name, so a zh_CN desktop has no
    # directory literally called "Downloads".
    write_user_dirs(linux, 'XDG_DOWNLOAD_DIR="$HOME/下载"\n')
    assert downloads_directory() == tmp_path / "下载"
    assert default_download_root() == tmp_path / "下载" / APP_NAME


def test_other_user_dirs_entries_are_not_mistaken_for_downloads(linux):
    write_user_dirs(
        linux,
        '# generated by xdg-user-dirs-update\nXDG_DESKTOP_DIR="$HOME/桌面"\n'
        'XDG_DOCUMENTS_DIR="$HOME/文档"\n',
    )
    assert downloads_directory() == linux / "Downloads"


@pytest.mark.parametrize("body", ['XDG_DOWNLOAD_DIR=""\n', 'XDG_DOWNLOAD_DIR="dl"\n'])
def test_blank_or_relative_download_entries_fall_back(linux, body):
    write_user_dirs(linux, body)
    assert downloads_directory() == linux / "Downloads"


def test_missing_user_dirs_file_falls_back(linux):
    assert not platform_paths._XDG_USER_DIRS.exists()
    assert downloads_directory() == linux / "Downloads"


def test_windows_downloads_use_the_shell_folder_registry(windows, tmp_path, monkeypatch):
    # Users move Downloads off the C: drive often enough that ~/Downloads is a
    # last resort, not the answer.
    moved = tmp_path / "D" / "Downloads"
    monkeypatch.setattr(platform_paths, "_windows_downloads_directory", lambda: moved)
    assert downloads_directory() == moved


def test_windows_downloads_fall_back_when_the_registry_is_unreadable(windows, monkeypatch):
    monkeypatch.setattr(platform_paths, "_windows_downloads_directory", lambda: None)
    assert downloads_directory() == windows / "Downloads"


@pytest.mark.parametrize(
    ("is_windows", "is_macos", "expected"),
    [(True, False, True), (False, True, True), (False, False, False)],
)
def test_case_folding_only_where_the_filesystem_folds(monkeypatch, is_windows, is_macos, expected):
    # Folding cache keys on Linux would let ``a.mp3`` reuse ``A.mp3``'s transcript.
    monkeypatch.setattr(platform_paths, "is_windows", lambda: is_windows)
    monkeypatch.setattr(platform_paths, "is_macos", lambda: is_macos)
    platform_paths.path_comparison_is_case_insensitive.cache_clear()
    try:
        assert platform_paths.path_comparison_is_case_insensitive() is expected
    finally:
        platform_paths.path_comparison_is_case_insensitive.cache_clear()
